<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Produk_model extends CI_Model
{

    public $table = 'produk';
    public $id = 'id_produk';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_produk', $q);
	$this->db->or_like('nama_produk', $q);
	$this->db->or_like('harga_produk', $q);
	// $this->db->or_like('stok_produk', $q);
	$this->db->or_like('gambar_produk', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_produk', $q);
	$this->db->or_like('nama_produk', $q);
	$this->db->or_like('harga_produk', $q);
	// $this->db->or_like('stok_produk', $q);
	$this->db->or_like('gambar_produk', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }
    function total_rows_pelanggan($q = NULL) {
        // $this->db->where('stok_produk >', '0');    
	$this->db->like('nama_produk', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data_pelanggan($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);

        $this->db->where('ketersediaan', 'Tersedia');    


        // $this->db->where('stok_produk >', '0');    
	$this->db->like('nama_produk', $q);

	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // delete bulkdata
    function deletebulk(){
        $data = $this->input->post('msg_', TRUE);
        $arr_id = explode(",", $data); 
        $this->db->where_in($this->id, $arr_id);
        return $this->db->delete($this->table);
    }

}

/* End of file Produk_model.php */
/* Location: ./application/models/Produk_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-08-04 06:17:22 */
/* http://harviacode.com */